WebSite/ShafaHRWebApplication/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShafaHRCoreLib.Attributes;
using ShafaHRCoreLib.Managers;
using ShafaHRCoreLib.Models;

namespace ShafaHRWebApplication.Controllers
{
    [AuthorizeAdmin]
    public class AdminController : BaseController
    {
        public ActionResult Index()
        {
            if (AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin)
            { return RedirectToAction("NotAccess", "Error"); }

            var roles = AuthorizationAdmin.Current.RoleS.ToList();

            List<SelectListItem> slItems = new List<SelectListItem>();

            AdminRole SelectedObject = null;

            foreach (AdminRole ur in roles)
            {

                SelectListItem slItem = new SelectListItem
                {
                    Selected = false
                };

                slItem.Text = CommonFunctions.GetDisplayName(ur.Role);

                if (ur.IsDefault) { SelectedObject = ur; slItem.Selected = true; }

                slItem.Value = ur.Id.ToString();
                slItems.Add(slItem);

            }


            if (SelectedObject != null)
            {
                ViewBag.Roles = new SelectList(slItems, "Value", "Text", SelectedObject.Id);
            }
            else
            {
                ViewBag.Roles = new SelectList(slItems, "Value", "Text");
            }

            return View(db.Admin.Where(u => u.RecordDeleted == false).OrderByDescending(r => r.Id).ToList());
        }


        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return RedirectToAction("Index", "Error");
            }

            if (id != AuthorizationAdmin.Current.AdminId && AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin)
            {

                return RedirectToAction("NotAccess", "Error");

            }

            Admin adminInfo_Exist = db.NotDeleted<Admin>().Where(u => u.Id == id).FirstOrDefault();

            if (adminInfo_Exist == null)
            {
                return RedirectToAction("NotFound", "Error");
            }

            return View(adminInfo_Exist);

        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id != AuthorizationAdmin.Current.AdminId && AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin)
            {
                return RedirectToAction("NotAccess", "Error");
            }

            Admin? admin_Exist = db.NotDeleted<Admin>().Where(u => u.Id == id).FirstOrDefault();

            if (admin_Exist == null)
            {
                return NotFound();
            }


            return View(admin_Exist);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Admin admin)
        {
            if (admin.Id != AuthorizationAdmin.Current.AdminId && AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin)
            {
                return RedirectToAction("NotAccess", "Error");
            }

            Admin? admin_Exist = db.NotDeleted<Admin>().Where(u => u.Id == admin.Id).FirstOrDefault();

            if (admin_Exist == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                //if (admin.Mobile != null && admin.Mobile != "" && db.Admin.Where(r => r.Mobile == admin.Mobile && r.Id != admin.Id && r.RecordDeleted == false).FirstOrDefault() != null)
                //{
                //    ViewBag.Message = "ثبت نام ناموفق! شماره همراه تکراری است.";
                //    return View(admin);
                //}

                if (admin.UserName != null && admin.UserName != "" && db.Admin.Where(r => r.Mobile == admin.UserName && r.Id != admin.Id && r.RecordDeleted == false).FirstOrDefault() != null)
                {
                    ViewBag.Message = "ثبت نام ناموفق! نام کاربری تکراری است.";
                    return View(admin);
                }



                admin_Exist.UserName = admin.UserName;
                admin_Exist.Firstname = admin.Firstname;
                admin_Exist.Lastname = admin.Lastname;
                admin_Exist.Mobile = admin.Mobile;

                db.Entry(admin_Exist).State = EntityState.Modified;

                admin_Exist.SetRecordDataForModify(db, admin.Id);

                db.SaveChanges();


                if (admin.Id == AuthorizationAdmin.Current.AdminId)
                {

                    AuthorizationAdmin.Current.Firstname = admin.Firstname;
                    AuthorizationAdmin.Current.Lastname = admin.Lastname;

                }

                return RedirectToAction("Index");
            }

            return View(admin);
        }

        public ActionResult Create()
        {

            if (AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin)
            {
                return RedirectToAction("NotAccess", "Error");
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Admin admin)
        {
            if (AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin)
            {
                return RedirectToAction("NotAccess", "Error");
            }

            if (ModelState.IsValid)
            {

                if (admin.UserName != null && db.NotDeleted<Admin>().Where(r => r.UserName.ToLower() == admin.UserName.Trim().ToLower()).FirstOrDefault() != null)
                {
                    ViewBag.Message = "ثبت نام ناموفق! نام کاربری تکراری است.";
                    return View(admin);
                }

                Admin admin_New = new Admin
                {
                    Firstname = admin.Firstname,
                    Lastname = admin.Lastname,
                    UserName = admin.UserName.Trim().ToLower(),
                    Mobile = admin.Mobile,
                    PasswordHash = CommonFunctions.GetSHA1(admin.PasswordHash)
                };

                db.Admin.Add(admin_New);
                db.SaveChanges();

                admin_New.SetRecordDataForCreate(db, AuthorizationAdmin.Current.AdminId);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return View(admin);
            }

        }
    }
}

WebSite/ShafaHRWebApplication/Controllers/PageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShafaHRCoreLib.Attributes;
using ShafaHRCoreLib.Managers;
using ShafaHRCoreLib.Models;

namespace ShafaHRWebApplication.Controllers
{
    public class PageController : BaseController
    {
        [AuthorizeAdmin]
        public IActionResult Index()
        {
            return View(db.NotDeleted<Page>());
        }

        [AuthorizeAdmin]
        public IActionResult Edit(long? Id)
        {
            if (Id == null || !long.TryParse(Id.ToString(), out long Id_Long)) return BadRequest();
            Page page_Exist = db.NotDeleted<Page>().FirstOrDefault(u => u.Id == Id);
            if (page_Exist == null) return NotFound();
            return View(page_Exist);
        }


        [AuthorizeAdmin]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Page? page_Posted, IFormCollection form_Posted)
        {

            if (page_Posted.Id == null || !long.TryParse(page_Posted.Id.ToString(), out long Id_Long)) return BadRequest();
            Page page_Exist = db.NotDeleted<Page>().FirstOrDefault(u => u.Id == page_Posted.Id);
            if (page_Exist == null) return NotFound();

            page_Exist.Title = page_Posted.Title;
            page_Exist.BodyHTML = form_Posted["area"].ToString().Replace("../..", "");


            db.Entry(page_Exist).State = EntityState.Modified;
            page_Exist.SetRecordDataForModify(db, AuthorizationAdmin.Current.AdminId);
            await db.SaveChangesAsync();
            ViewBag.Message = "ثبت با موفقیت انجام شد.";

            return View(page_Exist);
        }

        public IActionResult Details(string? Code)
        {
            if (string.IsNullOrEmpty(Code)) return BadRequest();
            Page page_Exist = db.NotDeleted<Page>().FirstOrDefault(u => u.Code == (EnumPageCode)Enum.Parse(typeof(EnumPageCode), Code));
            if (page_Exist == null) return NotFound();
            return View(page_Exist);
        }


        [HttpPost]
        public async Task<IActionResult> Image(IFormFile file)
        {
            if (file == null || file.Length == 0 || file.Length > 10000000)
                return BadRequest();

            if (Path.GetExtension(file.FileName) != ".jpg" && Path.GetExtension(file.FileName) != ".jpeg" && Path.GetExtension(file.FileName) != ".gif" && Path.GetExtension(file.FileName) != ".png" && Path.GetExtension(file.FileName) != ".webp" && Path.GetExtension(file.FileName) != ".pdf" && Path.GetExtension(file.FileName) != ".doc" && Path.GetExtension(file.FileName) != ".docx")
                return BadRequest();

            var uploads = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\uploads");

            if (!Directory.Exists(uploads))
                Directory.CreateDirectory(uploads);

            var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
            var filePath = Path.Combine(uploads, fileName);

            using var stream = new FileStream(filePath, FileMode.Create);
            await file.CopyToAsync(stream);

            return Json(new { location = "/uploads/" + fileName });
        }


        [HttpPost]
        public async Task<IActionResult> File(IFormFile file)
        {
            if (file == null || file.Length == 0)
                return BadRequest();

            var allowed = new[] { ".jpg", ".jpeg", ".png", ".webp", ".pdf", ".gif", ".doc", ".docx" };
            var ext = Path.GetExtension(file.FileName).ToLower();

            if (!allowed.Contains(ext))
                return BadRequest("قالب فایل صحیح نیست");

            if (file.Length > 10000000)
                return BadRequest("حجم فایل بیشتر از 10 مگ است");

            var uploads = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\uploads");
            if (!Directory.Exists(uploads))
                Directory.CreateDirectory(uploads);

            var fileName = Guid.NewGuid() + ext;
            var path = Path.Combine(uploads, fileName);

            using var stream = new FileStream(path, FileMode.Create);
            await file.CopyToAsync(stream);

            return Json(new { location = "/uploads/" + fileName });
        }
    }
}

WebSite/ShafaHRWebApplication/Controllers/SecurityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShafaHRCoreLib.Attributes;
using ShafaHRCoreLib.Managers;
using ShafaHRCoreLib.Models;
using System.Text;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace ShafaHRWebApplication.Controllers
{
    public class SecurityController : BaseController
    {
        public object JsonRequestBehavior { get; private set; }

        public IActionResult Index()
        {
            return View();
        }


       
        [HttpGet]
        public async Task<ActionResult> Login()
        {
            
            Admin? admin_Exist = db.NotDeleted<Admin>().Where(u => u.UserName == "admin").FirstOrDefault();

            if (admin_Exist == null)
            {
                Admin admin_New = new Admin
                {
                    Firstname = "ادمین",
                    Lastname = "سامانه",
                    UserName = "admin",
                    PasswordHash = CommonFunctions.GetSHA1("1234"),

                };

                db.Admin.Add(admin_New);

                AdminRole adminRole_New = new AdminRole
                {
                    Role = EnumAdminRole.SysAdmin,
                    Admin = admin_New,
                    IsDefault = true
                };

                db.AdminRole.Add(adminRole_New);

                await db.SaveChangesAsync();
            }
            else
            {
                if (admin_Exist.AdminRole.Where(r => r.RecordDeleted == false && r.Role == EnumAdminRole.SysAdmin).FirstOrDefault() == null)
                {
                    AdminRole adminRole_New = new AdminRole
                    {
                        Role = EnumAdminRole.SysAdmin,
                        Admin = admin_Exist
                    };

                    await db.SaveChangesAsync();
                }
            }

            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel LoginAdmin, string CaptchaInput)
        {
            var sessionCaptcha = HttpContext.Session.GetString("CaptchaCode");

            if (CaptchaInput.ToUpper() != sessionCaptcha)
            {
                ModelState.AddModelError("CaptchaInput", "متن اشتباه است");
                return View();
            }

            string LoginPassword = CommonFunctions.GetSHA1(CommonFunctions.GetEnglishNumber(LoginAdmin.Password));

            Admin? ui = db.NotDeleted<Admin>().Where(u => u.UserName == LoginAdmin.UserName.Trim() && u.PasswordHash == LoginPassword).FirstOrDefault();

            if (ui != null)
            {
                AuthorizationAdmin.Current.DoAuthenticatedAndHandleRoles(ui);

                return RedirectToAction("Dashboard", "Home");

            }
            else
            {
                ViewBag.message = "ورود ناموفق.";
            }

            return View();
        }

        public ActionResult Logout()
        {
            AuthorizationAdmin.Current.DoLogout();
            return RedirectToAction("Dashboard", "Home");
        }

        [AuthorizeAdmin]
        public ActionResult Setting()
        {
            var options = new DbContextOptionsBuilder<EFContext>().UseLazyLoadingProxies().UseSqlServer(CommonFunctions.ConnectionString).Options;
            EFContext? db = new EFContext(options);

            Admin? admin_Exist = db.NotDeleted<Admin>().FirstOrDefault(u => u.Id == AuthorizationAdmin.Current.AdminId);

            if (admin_Exist == null)
            {
                return NotFound();
            }

            return View(admin_Exist);
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        [AuthorizeAdmin]
        [HttpPost]
        public async Task<ActionResult> ChangePassword(ChangePasswordViewModel changePasswordViewModel)
        {
            if (ModelState.IsValid)
            {
                Admin? adminInfo = db.NotDeleted<Admin>().FirstOrDefault(u => u.Id == AuthorizationAdmin.Current.AdminId);

                if (adminInfo == null)
                {
                    ViewBag.Message = "اطلاعات کاربری صحیح نیست.";
                    return View(changePasswordViewModel);
                }

                if (changePasswordViewModel.NewPassword.Trim() != changePasswordViewModel.ConfirmPassword.Trim())
                {
                    ViewBag.Message = "کلمه عبور یکسان نیست.";
                    return View(changePasswordViewModel);
                }

                if (adminInfo.PasswordHash == CommonFunctions.GetSHA1(changePasswordViewModel.OldPassword.Trim()))
                {
                    adminInfo.PasswordHash = CommonFunctions.GetSHA1(changePasswordViewModel.NewPassword.Trim());

                    await db.SaveChangesAsync();
                    ViewBag.Message = "کلمه عبور با موفقیت تغییر یافت.";
                    return View(changePasswordViewModel);
                }

            }
            return View(changePasswordViewModel);
        }

       

        
    }
}

WebSite/ShafaHRWebApplication/Views/Shared/NavBar.cshtml
@using ShafaHRCoreLib.Managers
@using ShafaHRCoreLib.Models

<div class="left side-menu">
    <div class="sidebar-inner">

        <!-- User -->
        <div class="user-box">

            @if (AuthorizationAdmin.Current.IsAuthenticated)
            {
                <div class="user-img" style="display: none">
                    <img src="/assets/images/users/user.jpg" alt="user-img" title="" class="img-circle img-thumbnail img-responsive">
                    <div class="user-status offline"><i class="zmdi zmdi-dot-circle"></i></div>
                </div>

                <h5><a href="#">@AuthorizationAdmin.Current.Firstname @AuthorizationAdmin.Current.Lastname</a> </h5>

                <h4>

                    @if (AuthorizationAdmin.Current.Role != null)
                    {
                        @CommonFunctions.GetDisplayName(AuthorizationAdmin.Current.Role)
                    }

                </h4>

                <ul class="list-inline">

                    <li>
                        <a href="@Url.Action("Setting", "Security")" title="تنظیمات">
                            <i class="zmdi zmdi-settings"></i>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index", "AdminRole", new { AuthorizationAdmin.Current.AdminId })" title="تغییر نقش">
                            <i class="fa fa-users"></i>
                        </a>
                    </li>


                    <li>
                        <a href="@Url.Action("Logout", "Security")" class="text-custom" title="خروج از سامانه">
                            <i class="zmdi zmdi-power"></i>
                        </a>
                    </li>

                </ul>
            }
            else
            {
                <br />

                <a href="@Url.Action("Login", "Security")" style="color: #ffb300;font-weight: bold">ورود به سامانه</a>

            }
        </div>
        <!-- End User -->
        <!--- Sidemenu -->
        <div id="sidebar-menu">

            <ul>


                @if (AuthorizationAdmin.Current.IsAuthenticated)
                {
                    <li>
                        <a href="@Url.Action("Dashboard", "Home")" class="waves-effect"> <span> داشبورد </span> <i class="zmdi zmdi-view-dashboard"></i></a>
                    </li>

                    @if (AuthorizationAdmin.Current.Role == EnumAdminRole.SysAdmin)
                    {
                        <li>
                            <a href="@Url.Action("Index", "Admin")" class="waves-effect"> <span> فهرست ادمین </span><i class="fa fa-users"></i> </a>
                        </li>

                     
                    }

                    @if (AuthorizationAdmin.Current.Role == EnumAdminRole.SysAdmin || AuthorizationAdmin.Current.Role == EnumAdminRole.EditorPages)
                    {
                        <li>
                            <a href="@Url.Action("Index", "Page")" class="waves-effect"> <span> مدیریت صفحات </span><i class="fa fa-pencil"></i> </a>
                        </li>
                    }

                   
                    @if (AuthorizationAdmin.Current.Role == EnumAdminRole.SysAdmin || AuthorizationAdmin.Current.Role == EnumAdminRole.EditorPublications)
                    {
                        <li>
                            <a href="@Url.Action("Index", "Publication")" class="waves-effect"> <span> انتشارات </span><i class="fa fa-newspaper-o"></i> </a>
                        </li>
                    }
                                       


                    @if (AuthorizationAdmin.Current.Role == EnumAdminRole.SysAdmin)
                    {
                        <li>
                            <a href="@Url.Action("Dashboard", "Home")" class="waves-effect"> <span> گزارشات </span><i class="fa fa-users"></i> </a>
                        </li>
                    }

                }

            </ul>

            <div class="clearfix"></div>
        </div>
        <!-- Sidebar -->
        <div class="clearfix"></div>

    </div>

</div>