WebSite/ShafaHRWebApplication/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShafaHRCoreLib.Attributes;
using ShafaHRCoreLib.Managers;
using ShafaHRCoreLib.Models;

namespace ShafaHRWebApplication.Controllers
{
    [AuthorizeAdmin]
    public class AdminController : BaseController
    {
        public ActionResult Index()
        {
            if (AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin)
            { return RedirectToAction("NotAccess", "Error"); }

            var roles = AuthorizationAdmin.Current.RoleS.ToList();

            List<SelectListItem> slItems = new List<SelectListItem>();

            AdminRole SelectedObject = null;

            foreach (AdminRole ur in roles)
            {

                SelectListItem slItem = new SelectListItem
                {
                    Selected = false
                };

                slItem.Text = CommonFunctions.GetDisplayName(ur.Role);

                if (ur.IsDefault) { SelectedObject = ur; slItem.Selected = true; }

                slItem.Value = ur.Id.ToString();
                slItems.Add(slItem);

            }


            if (SelectedObject != null)
            {
                ViewBag.Roles = new SelectList(slItems, "Value", "Text", SelectedObject.Id);
            }
            else
            {
                ViewBag.Roles = new SelectList(slItems, "Value", "Text");
            }

            return View(db.Admin.Where(u => u.RecordDeleted == false).OrderByDescending(r => r.Id).ToList());
        }


        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return RedirectToAction("Index", "Error");
            }

            if (id != AuthorizationAdmin.Current.AdminId && AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin)
            {

                return RedirectToAction("NotAccess", "Error");

            }

            Admin adminInfo_Exist = db.NotDeleted<Admin>().Where(u => u.Id == id).FirstOrDefault();

            if (adminInfo_Exist == null)
            {
                return RedirectToAction("NotFound", "Error");
            }

            return View(adminInfo_Exist);

        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id != AuthorizationAdmin.Current.AdminId && AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin)
            {
                return RedirectToAction("NotAccess", "Error");
            }

            Admin? admin_Exist = db.NotDeleted<Admin>().Where(u => u.Id == id).FirstOrDefault();

            if (admin_Exist == null)
            {
                return NotFound();
            }


            return View(admin_Exist);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Admin admin)
        {
            if (admin.Id != AuthorizationAdmin.Current.AdminId && AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin)
            {
                return RedirectToAction("NotAccess", "Error");
            }

            Admin? admin_Exist = db.NotDeleted<Admin>().Where(u => u.Id == admin.Id).FirstOrDefault();

            if (admin_Exist == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                //if (admin.Mobile != null && admin.Mobile != "" && db.Admin.Where(r => r.Mobile == admin.Mobile && r.Id != admin.Id && r.RecordDeleted == false).FirstOrDefault() != null)
                //{
                //    ViewBag.Message = "ثبت نام ناموفق! شماره همراه تکراری است.";
                //    return View(admin);
                //}

                if (admin.UserName != null && admin.UserName != "" && db.Admin.Where(r => r.Mobile == admin.UserName && r.Id != admin.Id && r.RecordDeleted == false).FirstOrDefault() != null)
                {
                    ViewBag.Message = "ثبت نام ناموفق! نام کاربری تکراری است.";
                    return View(admin);
                }



                admin_Exist.UserName = admin.UserName;
                admin_Exist.Firstname = admin.Firstname;
                admin_Exist.Lastname = admin.Lastname;
                admin_Exist.Mobile = admin.Mobile;

                db.Entry(admin_Exist).State = EntityState.Modified;

                admin_Exist.SetRecordDataForModify(db, admin.Id);

                db.SaveChanges();


                if (admin.Id == AuthorizationAdmin.Current.AdminId)
                {

                    AuthorizationAdmin.Current.Firstname = admin.Firstname;
                    AuthorizationAdmin.Current.Lastname = admin.Lastname;

                }

                return RedirectToAction("Index");
            }

            return View(admin);
        }

        public ActionResult Create()
        {

            if (AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin)
            {
                return RedirectToAction("NotAccess", "Error");
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Admin admin)
        {
            if (AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin)
            {
                return RedirectToAction("NotAccess", "Error");
            }

            if (ModelState.IsValid)
            {

                if (admin.UserName != null && db.NotDeleted<Admin>().Where(r => r.UserName.ToLower() == admin.UserName.Trim().ToLower()).FirstOrDefault() != null)
                {
                    ViewBag.Message = "ثبت نام ناموفق! نام کاربری تکراری است.";
                    return View(admin);
                }

                Admin admin_New = new Admin
                {
                    Firstname = admin.Firstname,
                    Lastname = admin.Lastname,
                    UserName = admin.UserName.Trim().ToLower(),
                    Mobile = admin.Mobile,
                    PasswordHash = CommonFunctions.GetSHA1(admin.PasswordHash)
                };

                db.Admin.Add(admin_New);
                db.SaveChanges();

                admin_New.SetRecordDataForCreate(db, AuthorizationAdmin.Current.AdminId);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return View(admin);
            }

        }
    }
}

WebSite/ShafaHRWebApplication/Controllers/AdminRoleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShafaHRCoreLib.Attributes;
using ShafaHRCoreLib.Managers;
using ShafaHRCoreLib.Models;

namespace ShafaHRWebApplication.Controllers
{
    [AuthorizeAdmin]
    public class AdminRoleController : BaseController
    {
        // GET: AdminRole

        public ActionResult Index(int? AdminId)
        {
            if (AdminId == null)
            {
                return RedirectToAction("NotAccess", "Error");
            }

            if (AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin && AuthorizationAdmin.Current.AdminId != AdminId)
            {
                return RedirectToAction("NotAccess", "Error");
            }

            Admin admin_Exist = db.NotDeleted<Admin>().Where(u => u.Id == AdminId).FirstOrDefault();

            if (admin_Exist == null) { return RedirectToAction("NotFound", "Error"); }

            ViewBag.AdminId = AdminId;
            ViewBag.AdminFullName = admin_Exist.Firstname + ' ' + admin_Exist.Lastname;

            return View(admin_Exist.AdminRole?.Where(u => u.RecordDeleted == false).ToList());
        }

        public ActionResult Create(int? Id)
        {

            if (AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin)
            {
                return RedirectToAction("NotAccess", "Error");
            }

            Admin admin_Exist = db.NotDeleted<Admin>().Where(u => u.Id == Id).FirstOrDefault();

            if (admin_Exist == null) { return RedirectToAction("NotFound", "Error"); }

            ViewBag.AdminId = Id;
            ViewBag.AdminFullName = admin_Exist.Firstname + ' ' + admin_Exist.Lastname;

            AdminRole adminRole_New = new AdminRole() { AdminId = admin_Exist.Id };

            return View(adminRole_New);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AdminRole adminRole)
        {
            if (adminRole.Id == 0)
            {
                return RedirectToAction("NotAccess", "Error");
            }

            if (AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin)
            {
                return RedirectToAction("NotAccess", "Error");
            }

            Admin admin_Exist = db.NotDeleted<Admin>().Where(u => u.Id == adminRole.AdminId).FirstOrDefault();

            if (admin_Exist == null) { return RedirectToAction("NotFound", "Error"); }


            ViewBag.AdminFullName = admin_Exist.Firstname + ' ' + admin_Exist.Lastname;

            SelectListItem s = new SelectListItem
            {
                Text = "-- بیمارستان --",
                Value = "",
                Selected = true
            };

            if (admin_Exist.AdminRole.Where(u => u.RecordDeleted == false && u.Role == adminRole.Role).FirstOrDefault() != null)
            {
                return RedirectToAction("Index", new { id = admin_Exist.Id });
            }


            AdminRole adminRole_New = new AdminRole
            {
                AdminId = admin_Exist.Id,
                Role = adminRole.Role

            };

            db.AdminRole.Add(adminRole_New);
            adminRole_New.SetRecordDataForCreate(db, AuthorizationAdmin.Current.AdminId);


            db.SaveChanges();

            return RedirectToAction("Index", new { AdminId = admin_Exist.Id });

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult IsDefault(int? roleId, bool? IsDefault, int? adminId)
        {

            if (roleId == null || IsDefault == null || adminId == null)
            {
                return RedirectToAction("NotAccess", "Error");
            }

            if (AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin && AuthorizationAdmin.Current.AdminId != adminId)
            {
                return RedirectToAction("NotAccess", "Error");
            }

            Admin admin_Exist = db.Admin.Where(u => u.RecordDeleted == false && u.Id == adminId).FirstOrDefault();

            if (admin_Exist == null) { return RedirectToAction("NotFound", "Error"); }

            if (admin_Exist.AdminRole == null) { return RedirectToAction("NotAccess", "Error"); }


            AdminRole adminRole_Exist = admin_Exist.AdminRole.Where(u => u.RecordDeleted == false && u.Id == roleId).FirstOrDefault();

            if (adminRole_Exist == null) { return RedirectToAction("NotAccess", "Error"); }


            adminRole_Exist.IsDefault = (bool)IsDefault;

            db.Entry(adminRole_Exist).State = EntityState.Modified;

            if (admin_Exist.AdminRole.Count > 1)
            {
                foreach (AdminRole UR in admin_Exist.AdminRole)
                {
                    if (UR.Id != roleId)
                    {
                        UR.IsDefault = false;
                        db.Entry(UR).State = EntityState.Modified;
                    }
                }
            }

            db.SaveChanges();

            return RedirectToAction("Index", new { AdminId = admin_Exist.Id });
        }


        [AuthorizeAdmin]
        public async Task<ActionResult> Delete(long? Id)
        {
            if (AuthorizationAdmin.Current.Role != EnumAdminRole.SysAdmin || Id == null || !long.TryParse(Id.ToString(), out long Id_Long))
            {
                return RedirectToAction("Dashboard", "Home");
            }

            AdminRole adminRole_Exist = db.NotDeleted<AdminRole>().Where(u => u.Id == Id).FirstOrDefault();

            if (adminRole_Exist == null)
            {
                return RedirectToAction("Dashboard", "Home");
            }

            adminRole_Exist.RecordDeleted = true;

            db.Entry(adminRole_Exist).State = EntityState.Modified;

            adminRole_Exist.SetRecordDataForDelete(db, AuthorizationAdmin.Current.AdminId);

            await db.SaveChangesAsync();

            return RedirectToAction("Index", new { adminRole_Exist.AdminId });
        }
    }
}

WebSite/ShafaHRWebApplication/Controllers/SecurityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShafaHRCoreLib.Attributes;
using ShafaHRCoreLib.Managers;
using ShafaHRCoreLib.Models;
using System.Text;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace ShafaHRWebApplication.Controllers
{
    public class SecurityController : BaseController
    {
        public object JsonRequestBehavior { get; private set; }

        public IActionResult Index()
        {
            return View();
        }


       
        [HttpGet]
        public async Task<ActionResult> Login()
        {
            
            Admin? admin_Exist = db.NotDeleted<Admin>().Where(u => u.UserName == "admin").FirstOrDefault();

            if (admin_Exist == null)
            {
                Admin admin_New = new Admin
                {
                    Firstname = "ادمین",
                    Lastname = "سامانه",
                    UserName = "admin",
                    PasswordHash = CommonFunctions.GetSHA1("1234"),

                };

                db.Admin.Add(admin_New);

                AdminRole adminRole_New = new AdminRole
                {
                    Role = EnumAdminRole.SysAdmin,
                    Admin = admin_New,
                    IsDefault = true
                };

                db.AdminRole.Add(adminRole_New);

                await db.SaveChangesAsync();
            }
            else
            {
                if (admin_Exist.AdminRole.Where(r => r.RecordDeleted == false && r.Role == EnumAdminRole.SysAdmin).FirstOrDefault() == null)
                {
                    AdminRole adminRole_New = new AdminRole
                    {
                        Role = EnumAdminRole.SysAdmin,
                        Admin = admin_Exist
                    };

                    await db.SaveChangesAsync();
                }
            }

            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel LoginAdmin, string CaptchaInput)
        {
            var sessionCaptcha = HttpContext.Session.GetString("CaptchaCode");

            if (CaptchaInput.ToUpper() != sessionCaptcha)
            {
                ModelState.AddModelError("CaptchaInput", "متن اشتباه است");
                return View();
            }

            string LoginPassword = CommonFunctions.GetSHA1(CommonFunctions.GetEnglishNumber(LoginAdmin.Password));

            Admin? ui = db.NotDeleted<Admin>().Where(u => u.UserName == LoginAdmin.UserName.Trim() && u.PasswordHash == LoginPassword).FirstOrDefault();

            if (ui != null)
            {
                AuthorizationAdmin.Current.DoAuthenticatedAndHandleRoles(ui);

                return RedirectToAction("Dashboard", "Home");

            }
            else
            {
                ViewBag.message = "ورود ناموفق.";
            }

            return View();
        }

        public ActionResult Logout()
        {
            AuthorizationAdmin.Current.DoLogout();
            return RedirectToAction("Dashboard", "Home");
        }

        [AuthorizeAdmin]
        public ActionResult Setting()
        {
            var options = new DbContextOptionsBuilder<EFContext>().UseLazyLoadingProxies().UseSqlServer(CommonFunctions.ConnectionString).Options;
            EFContext? db = new EFContext(options);

            Admin? admin_Exist = db.NotDeleted<Admin>().FirstOrDefault(u => u.Id == AuthorizationAdmin.Current.AdminId);

            if (admin_Exist == null)
            {
                return NotFound();
            }

            return View(admin_Exist);
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        [AuthorizeAdmin]
        [HttpPost]
        public async Task<ActionResult> ChangePassword(ChangePasswordViewModel changePasswordViewModel)
        {
            if (ModelState.IsValid)
            {
                Admin? adminInfo = db.NotDeleted<Admin>().FirstOrDefault(u => u.Id == AuthorizationAdmin.Current.AdminId);

                if (adminInfo == null)
                {
                    ViewBag.Message = "اطلاعات کاربری صحیح نیست.";
                    return View(changePasswordViewModel);
                }

                if (changePasswordViewModel.NewPassword.Trim() != changePasswordViewModel.ConfirmPassword.Trim())
                {
                    ViewBag.Message = "کلمه عبور یکسان نیست.";
                    return View(changePasswordViewModel);
                }

                if (adminInfo.PasswordHash == CommonFunctions.GetSHA1(changePasswordViewModel.OldPassword.Trim()))
                {
                    adminInfo.PasswordHash = CommonFunctions.GetSHA1(changePasswordViewModel.NewPassword.Trim());

                    await db.SaveChangesAsync();
                    ViewBag.Message = "کلمه عبور با موفقیت تغییر یافت.";
                    return View(changePasswordViewModel);
                }

            }
            return View(changePasswordViewModel);
        }

       

        
    }
}

WebSite/ShafaHRWebApplication/Views/Security/ChangePassword.cshtml
@model ShafaHRCoreLib.Models.ChangePasswordViewModel

@{
    ViewBag.Title = "پژوهشگران سلامت شفا";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card-box" style="padding: 30px">

    <div class="row">
        <div class="col-md-12" style="padding:15px;background-color: #367656">
            @Html.ActionLink("تنظیمات", "Setting", "Account")
            <span style="font-size: 8pt">&nbsp;&nbsp;>>&nbsp;&nbsp; </span>
            <span style="font-size: 14pt;color: #959595"> تغییر کلمه عبور</span>
        </div>
    </div>

    <div class="row">
        <div class="col-md 12" style="height:10px">
        </div>
    </div>

    @using (Html.BeginForm())
    {


        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                @Html.LabelFor(model => model.OldPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OldPassword, new { htmlAttributes = new { @class = "form-control", maxlength = "20", type = "Password" } })
                    @Html.ValidationMessageFor(model => model.OldPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control", maxlength = "20", type = "Password" } })
                    @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control", maxlength = "20", type = "Password" } })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-2" style="text-align: left;"></div>
                <div class="col-md-10" style="text-align: right;">
                    <button type="submit" class="btn btn-success btn-trans waves-effect w-md waves-success m-b-5">ثبت</button>
                </div>
            </div>

        </div>
    }



</div>

WebSite/ShafaHRWebApplication/Views/Security/Login.cshtml
@model ShafaHRCoreLib.Models.LoginViewModel
@using ShafaHRCoreLib.Managers

@{
    ViewData["Title"] = "ورود به سامانه";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>

    <meta name="viewport" content="width=device-width" />
    
    <title>ورود به سامانه</title>
    <!-- App CSS -->
    <link href="/assets/css/bootstrap-rtl.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/core.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/components.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/pages.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/menu.css" rel="stylesheet" type="text/css" />
    <link href="/assets/css/responsive.css" rel="stylesheet" type="text/css" />


    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="/assets/js/modernizr.min.js"></script>
</head>
<body>
    <div class="account-pages"></div>
    <div class="clearfix"></div>
    <div class="wrapper-page">
        <div class="text-right">
            <a href="@Url.Action("Index", "Home")" class="logo text-center">
                <h2 style="color: white; font-size: 20pt;text-shadow: 1px 1px 2px black, 0 0 25px green, 0 0 5px #000;">پژوهشگران سلامت شفا</h2>
            </a>
        </div>
        <div class="m-t-10 card-box" style="opacity:0.9;border-radius: 25px;">
            <div class="text-center text-black" style="font-size: 16pt;margin-top: 20px">
                ورود به سامانه
            </div>
            <div class="panel-body">
                <div style="color: red;text-align: right;direction: rtl">
                    @Html.ValidationSummary()

                </div>
                <form class="form-horizontal m-t-20" action="/security/login" method="post">

                    <div class="form-group ">
                        <div class="col-xs-12 text-center" style="font-family: 'iran'">
                            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", placeholder = "نام کاربری", maxlength = "50", required = "", style = "direction:ltr" } })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-12 text-center" style="font-family: 'iran'">
                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", placeholder = "کلمه عبور", maxlength = "20", required = "", type = "Password", style = "direction:ltr" } })
                        </div>
                    </div>

                    <div class="form-group">

                        <div class="col-md-1" style="align-items:center;">

                            <i class="fa fa-refresh fw-bolder pt-3" style="cursor:pointer;"
                               title="رفرش کپچا" onclick="reloadCaptcha()"></i>
                        </div>
                        <div class="col-md-11" id="captchaContainer">
                            @await Component.InvokeAsync("Captcha")
                        </div>
                    </div>


                    <div class="form-group text-center text-white">
                        <div class="col-md-12">
                            <button class="btn btn-success waves-effect w-md waves-light m-b-5 " type="submit">ورود</button>

                        </div>
                    </div>

                    @*<div class="form-group m-t-30 m-b-0" style="display: none">
                            <div class="col-sm-12" dir="rtl">
                                <a href="page-recoverpw.html" class="text-muted"><i class="fa fa-lock m-r-5"></i> آیا رمز خود را فراموش کرده اید؟</a>
                            </div>
                        </div>*@
                </form>



            </div>
        </div>

        <!-- end card-box-->




    </div>
    <!-- end wrapper page -->

    <div class="row">
        <div class="col-md-12 text-black" style="font-size: 9pt;direction: rtl">
            <center>
                © @CommonFunctions.GetPersianDate(DateTime.Now).Substring(0, 4) پژوهشگران سلامت شفا، تمام حقوق محفوظ است.
            </center>
        </div>
    </div>

    <script>
        var resizefunc = [];
    </script>

    <!-- jQuery  -->
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/bootstrap-rtl.min.js"></script>
    <script src="/assets/js/detect.js"></script>
    <script src="/assets/js/fastclick.js"></script>
    <script src="/assets/js/jquery.slimscroll.js"></script>
    <script src="/assets/js/jquery.blockUI.js"></script>
    <script src="/assets/js/waves.js"></script>
    <script src="/assets/js/wow.min.js"></script>
    <script src="/assets/js/jquery.nicescroll.js"></script>
    <script src="/assets/js/jquery.scrollTo.min.js"></script>

    <!-- App js -->
    <script src="/assets/js/jquery.core.js"></script>
    <script src="/assets/js/jquery.app.js"></script>
    <script>

        function reloadCaptcha() {
            fetch('/Captcha/Reload')
                .then(res => res.text())
                .then(html => {
                    document.getElementById('captchaContainer').innerHTML = html;
                });
        }

    </script>
</body>
</html>

WebSite/ShafaHRWebApplication/Views/Security/Setting.cshtml
@model ShafaHRCoreLib.Models.Admin
@using ShafaHRCoreLib.Managers

@{
    ViewBag.Title = "پژوهشگران سلامت شفا";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card-box" style="padding: 30px">
    <div class="row">
        <div class="col-md-12" style="padding:15px;background-color: #367656">
            <span style="font-size: 16pt;color: #ffffff"> تنظیمات </span>
        </div>
    </div>
    <div class="row">
        <div class="col-md 12" style="height:10px">
        </div>
    </div>
    <p>
        <a href="@Url.Action("Details", "Admin", new { Id = Model.Id })"><i class="fa fa-user"></i>&nbsp; <span> پروفایل  من </span> </a>
    </p>
    <p>
        <a href="@Url.Action("Index", "AdminRole", new { Id = AuthorizationAdmin.Current.AdminId })"><i class="fa fa-users"></i>&nbsp; <span> نقش های من </span> </a>
    </p>
    <p>
        <a href="@Url.Action("ChangePassword", "Security", new { Id = Model.Id })"><i class="fa fa-expeditedssl">&nbsp;</i> <span> تغییر کلمه عبور </span> </a>
    </p>

</div>